# Generated by Django 6.0.1 on 2026-01-24 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuoustask',
            name='on_going',
        ),
    ]
